version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://www.oncloudconsulting/
      - aws cloudfront create-invalidation --distribution-id E7HIBIR35Q2PN --path/\*